---
 - name: "Site24x7 MySQL Plugin Installation"
   hosts: localhost
   become: yes
   vars:
      credential:
        - mysql_node: "172.17.0.3"
          username: "site24x7"
          password: "site24x7"
        - mysql_node: "127.0.0.1"
          username: "root"
          password: ""
      port: 3306 
      logs_enabled: true
      log_type_name: '"Mysql General Logs"'
      log_file_path: '"/var/log/mysql/error.log"'


  
   tasks:    
  # Site24x7 MySQL Prerequisites Check

   - name: "Python3 Installation Check."
     command: "python3 --version"
     register: python_version_output
     ignore_errors: yes

   - name: "Installing Python if not found (for Debian/Ubuntu)."
     apt:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing Python if not found (for CentOS/RedHat)."
     yum:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "pip3 Installation Check."
     command: "pip3 --version"
     register: pip_version_output
     ignore_errors: yes


   - name: "Installing pip3 if not found (for Debian/Ubuntu)."
     apt:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'Debian'"


   - name: "Installing pip3 if not found (for RedHat/CentOS)."
     yum:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

      
   - name: "Installing pymysql Python3 Package."
     pip:
        name: pymysql
        state: present
        executable: pip3
     ignore_errors: yes


   - name: pymysql check
     shell: 'python3 -c "import pymysql"'
     register: pymysql_status
     ignore_errors: yes

   - set_fact: 
      pymysql_stats: "{{pymysql_status.rc}}"


   - name: "Site24x7 Agent Directory Check."
     stat:
      path: "/opt/site24x7/monagent/temp"
     register: agent_path_check

   - name: "Hosts with no Site24x7 Agent Directory"
     debug:
      msg: "Agent Directory not found"
     when: not agent_path_check.stat.exists


   - name: "Site24x7 Temp Plugins Directory Creation."
     file:
      path: "/opt/site24x7/monagent/temp/plugins/mysql"
      state: directory
     when: agent_path_check.stat.exists

   - name: "Site24x7 Plugin Directory Check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/mysql"
     register: plugin_path_check

   - name: "Download the Site24x7 pymysql library"
     get_url:
        url: "https://github.com/site24x7/plugins/raw/master/mysql/pymysql/pymysql.zip"
        dest: "/opt/site24x7/monagent/temp/plugins/mysql"
        mode: 0744
     when: plugin_path_check.stat.exists and pymysql_stats !=0

   - name: "MySQL pymysql module check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/mysql/pymysql.zip"
     register: pymysql_path_check

   - name: "unzip the module"
     unarchive:
        src: /opt/site24x7/monagent/temp/plugins/mysql/pymysql.zip   # Path to your archive file
        dest: /opt/site24x7/monagent/temp/plugins/mysql      # Destination directory where the content will be extracted
        remote_src: yes 
     when: pymysql_path_check.stat.exists and pymysql_stats!=0

   - name: "Download the Site24x7 MySQL Plugin Files."
     get_url:
        url: "{{ item }}"
        dest: "/opt/site24x7/monagent/temp/plugins/mysql"
        mode: 0744
     loop: ["https://raw.githubusercontent.com/site24x7/plugins/master/mysql/mysql.py","https://raw.githubusercontent.com/site24x7/plugins/master/mysql/mysql.cfg"]
     when: plugin_path_check.stat.exists and (pymysql_path_check.stat.exists or pymysql_stats ==0)
    

  # Site24x7 MySQL Plugin Config File Setup
  
   - name: "Site24x7 MySQL Config File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/mysql/mysql.cfg"
     register: mysql_file_check

   - name: "Remove existing content from .cfg file"
     copy:
       dest: "/opt/site24x7/monagent/temp/plugins/mysql/mysql.cfg"
       content: ""
     when: mysql_file_check.stat.exists
   
   - name: "Loop the mysql_node"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/mysql/mysql.cfg"
       line: |
         [ {{item.mysql_node}} ]
         host = {{item.mysql_node}}
         port = {{port}}
         username = {{item.username}}
         password = {{item.password}}
         logs_enabled= {{logs_enabled}}
         log_type_name= {{log_type_name}}
         log_file_path= {{log_file_path}}
       
     loop: "{{credential}}" 
     loop_control: 
       loop_var: item
     when: mysql_file_check.stat.exists

  # Site24x7 MySQL Python File Setup

   - name: "Site24x7 MySQL Python File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/mysql/mysql.py"
     register: mysql_python_file_check

   - name: "Extracting Python3 Default Path."
     command: which python3
     register: python3_path

   - set_fact:
      actual_path: "{{ '#!'+python3_path.stdout }}"

   - name: "Setting the Default Python Path for the Site24x7 MySQL Plugin"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/mysql/mysql.py"
       regexp: "#!"
       line: "{{actual_path}}"
     when: mysql_python_file_check.stat.exists

   - name: "Checking the Site24x7 MySQL Plugin Output"
     shell: "python3 /opt/site24x7/monagent/temp/plugins/mysql/mysql.py --host={{item.mysql_node}} --port={{port}} --username={{item.username}} --password={{item.password}}"
     register: mysql_python_output
     when: mysql_python_file_check.stat.exists
     loop: "{{credential}}"

   - name: "Site24x7 MySQL plugins with Error !"
     debug:
      msg: "Site24x7 MySQL Plugin OUTPUT error ! "
     when: "'All items completed' not in mysql_python_output.msg and mysql_python_file_check.stat.exists"

   - name: "Moving the Site24x7 MySQL Folder to the Plugins Directory"
     command: "mv  /opt/site24x7/monagent/temp/plugins/mysql /opt/site24x7/monagent/plugins"
     ignore_errors: true
     when: "plugin_path_check.stat.exists and 'All items completed' in mysql_python_output.msg"
